// Utility to map Tailwind classes to custom CSS classes
export const cn = (...classes) => {
  return classes.filter(Boolean).join(' ')
    // Replace common Tailwind patterns with custom classes
    .replace(/bg-white\/10/g, 'bg-white-10')
    .replace(/bg-white\/90/g, 'bg-white-90')
    .replace(/hover:bg-gray-100/g, 'hover-bg-gray-100')
    .replace(/hover:bg-gray-700/g, 'hover-bg-gray-700')
    .replace(/hover:bg-red-50/g, 'hover-bg-red-50')
    .replace(/hover:text-white/g, 'hover-text-white')
    .replace(/hover:text-gray-700/g, 'hover-text-gray-700')
    .replace(/hover:border-gray-300/g, 'hover-border-gray-300')
    .replace(/hover:shadow-md/g, 'hover-shadow-md')
    .replace(/hover:shadow-lg/g, 'hover-shadow-lg')
    .replace(/hover:shadow-xl/g, 'hover-shadow-xl')
    .replace(/hover:scale-105/g, 'hover-scale-105')
    .replace(/hover:scale-110/g, 'hover-scale-110')
    .replace(/group-hover:scale-105/g, 'group-hover-scale-105')
    .replace(/group-hover:scale-110/g, 'group-hover-scale-110')
    .replace(/group-hover:shadow-lg/g, 'group-hover-shadow-lg')
    .replace(/focus:ring-2/g, 'focus-ring-2')
    .replace(/focus:ring-primary-500/g, 'focus-ring-primary-500')
    .replace(/focus:border-transparent/g, 'focus-border-transparent')
    .replace(/max-h-\[90vh\]/g, 'max-h-90vh')
    .replace(/-translate-x-1\/2/g, 'translate-x-neg-half')
    .replace(/-translate-y-1\/2/g, 'translate-y-neg-half')
    .replace(/sm:/g, 'sm-')
    .replace(/md:/g, 'md-')
    .replace(/lg:/g, 'lg-')
}